project:
  type: website

website:
  title: "Chasten Documentation"
  navbar:
    left:
      - href: chastenwiki.qmd
      - href: videos.qmd
      - href: devforum.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



